#!/bin/bash

# better names for parameters
# Nagios virtualenv base directory (established by "virtualenv" command)
NAGIOS_VENV_DIR=$1
SERVER=$2
USERNAME=$3
PASSWORD=$4
# optional parameters: must both be absent, or both present; else Python script will barf
WARNLEVEL=$5
CRITLEVEL=$6

# virtualenv: activate the nagios virtualenv
. $NAGIOS_VENV_DIR/bin/activate

# what's this script's directory? (WARNING: can break if current dir reached via symlink)
SCRIPT_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

# ASSUMPTION: the Python script is colocated in $SCRIPT_DIR
python $SCRIPT_DIR/tomcat_mem_usage.py $SERVER $USERNAME $PASSWORD $WARNLEVEL $CRITLEVEL
# capture the python script's exit status 
STATUS_CODE=$?

# virtualenv: deactivate the nagios virtualenv
. $NAGIOS_VENV_DIR/bin/deactivate

exit $STATUS_CODE
